export const GOOGLE_MAPS_LOGO_HEIGHT = 38;
export const GAS_STATION_ITEM_HEIGHT = 295;
export const REGION_SELECTOR_HEIGHT = 58;
export const ITEM_MARGIN = 8;
export const MAP_PADDING_BOTTOM =
  GOOGLE_MAPS_LOGO_HEIGHT +
  GAS_STATION_ITEM_HEIGHT +
  ITEM_MARGIN +
  REGION_SELECTOR_HEIGHT +
  ITEM_MARGIN;
